on: 
  push:
    branches: [main]
name: Build and Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env
          echo GATSBY_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} >> .env
          echo GATSBY_MAP_ID=${{ secrets.MAP_ID }} >> .env
          cat .env

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 136.243.40.198
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: httpdocs/
          dry-run: false
